### ISSUE TITLE
Stream output?

### ISSUE THREAD

**Issue by brandonchinn178** [BurntSushi/toml-test#114]
Is it possible to stream the output instead of waiting until all the tests are complete? That way, you can see the progress, especially with `--verbose`, to see progress of passing tests

**Comment by arp242** [comment]
You can't do this right now; it runs all the tests, collects the results, and then prints that.

The reason it works like this is so it's a bit more flexible: you can run the tests from your (Go) code and then do $something_else with it instead of just printing to the terminal. I expected it to be "fast enough" that it doesn't really matter; but I guess not (or at least, not with your specific TOML library)?

Could add callbacks or the like instead; but it's unlikely I'll work on it myself any time soon, but I'll review and merge patches.

**Comment by brandonchinn178** [comment]
Yeah, a callback is probably the answer. It is fast enough right now; it's just a bit of a nice-to-have. Not important. I don't know Go, so I won't be able to make a contribution, but maybe a good first issue for someone wanting to help out later?

**Comment by arp242** [comment]
Right now it takes about 400ms:

    % time toml-test toml-test-decoder >/dev/null 2>&1
    toml-test toml-test-decoder > /dev/null 2>&1  0.13s user 0.30s system 108% cpu 0.396 total

This is on my *slow* 1.1GHz Celeron laptop; I can't be bothered to try it on my other machine right now. Even if we double the number of tests (unlikely!) it should still be plenty fast enough.

If someone really wants to work on it they can and I'll merge PRs, but I'll close this issue for now so it's off my "todo list" since I don't foresee I'll ever work on this.
