### ISSUE TITLE
Encoder tests fail due to missing directory

### ISSUE THREAD

**Issue by awvwgk** [BurntSushi/toml-test#117]
There is no `tests/invalid-encoder` directory anymore in this repository and using `toml-test` with the `-encoder` option therefore fails. A quick workaround is to create the directory `tests/invalid-encoder` after checking out `toml-test` locally or in a CI workflow.

Having a simple invalid encoder test like a top-level array or just an empty file like `.gitkeep` might be useful to preserve the directory.

**Comment by arp242** [comment]
The directory not existing shouldn't be an error: https://github.com/BurntSushi/toml-test/blob/master/runner.go#L193-L197

Can you tell me which version you're using? And if you compiled it yourself, with which Go version?

**Comment by arp242** [comment]
Ah, I see now it only fails if you use `-testdir`; I just committed a fix.

**Comment by awvwgk** [comment]
Thanks for the quick fix. I was indeed using `-testdir` to run `toml-test` inside a meson build.

**Comment by arp242** [comment]
You don't really need to specify the `-testdir` flag, since the `toml-test` binary embeds the tests in the binary itself, and will use those if the flag is omitted. The binary itself should be the only thing you need unless you want to add new tests yourself.

As an side, looking at [your PR over here](https://github.com/toml-f/toml-f/pull/73/files), would it be helpful for you if a `toml-test -ls` command was added? Not sure why you loop over all the tests like this, but having to copy a list of files like that isn't too great.

**Comment by awvwgk** [comment]
The loop is only necessary because I just upgraded `toml-test` and found a couple of tests are not working due to a format change in the JSON representation, I think I forked `toml-test` in late 2019/early 2020 when the repo was stale (many thanks for taking over the maintenance!). Once I adjust my JSON serializer and deserializer I can probably remove them and let `toml-test` handle the tests again, but at the moment it's easier to have them individually in meson to go through all the broken ones case by case.
