### ISSUE TITLE
Inconsistent arrays test expectations

### ISSUE THREAD

**Issue by redhotvengeance** [BurntSushi/toml-test#12]
I'm implementing support for `toml-test` and have found what seems like an inconsistency in the expectations for a few of the tests - specifically for the table arrays.

With non-table arrays, it is expected that the JSON output specifies `array` for `type`, ala the example in [/tests/valid/arrays.json](https://github.com/BurntSushi/toml-test/blob/master/tests/valid/arrays.json) where this TOML:

``` toml
strings = ["a", "b", "c"]
```

...would output this JSON:

``` json
{
  "strings": {
    "type": "array",
    "value": [
      {"type": "string", "value": "a"},
      {"type": "string", "value": "b"},
      {"type": "string", "value": "c"}
    ]
  }
}
```

However, with the table arrays, the expected JSON output is showing **not** to expect a specified type at all, ala the example in [/tests/valid/table-array-one.json](https://github.com/BurntSushi/toml-test/blob/master/tests/valid/table-array-one.json) where this TOML:

``` toml
[[people]]
first_name = "Bruce"
last_name = "Springsteen"
```

...is expecting this JSON:

``` json
{
  "people": [
    {
      "first_name": {"type": "string", "value": "Bruce"},
      "last_name": {"type": "string", "value": "Springsteen"}
    }
  ]
}
```

Since the resulting data structure is is that `people` is array like any other (an array of objects), I would expect `people` be typed like all other arrays, like this:

``` json
{
  "people": {
    "type": "array",
    "value": [
      {
        "first_name": {"type": "string", "value": "Bruce"},
        "last_name": {"type": "string", "value": "Springsteen"}
      }
    ]
  }
}
```

What's the reason for the different expectations?

**Comment by mmakaay** [comment]
I would rather see that inline arrays are always seen as array, while table arrays are seen as table arrays. There's a clear distinction between the two in TOML. One is static, the other is not. Table arrays can be extended by defining more of them, while inline arrays cannot be modified.

However, I noticed when testing my parser that this code:
`oo = [ { bar="\"{{baz}}\""} ]`

is expected to be outputted as:
``` golang
{
  "foo": [
    {
        "bar": {"type": "string", "value": "\"{{baz}}\"" }
    }
  ]
}
```
So a table array, even though it was defined as a static array.
Yes, I can detect that it contains inline tables, so I will have to go that path right now to make your test suite work, but it feels wrong because the json no longer represents the semantics of the types.
In my parser, a table is a value as well, and there's no real distinction between "array of integers" and "array of tables".

**Comment by trevorld** [comment]
In the [Array of Tables](https://toml.io/en/v1.0.0#array-of-tables) section of TOML v1.0 it explicitly says that "you may also use inline tables where appropriate" instead of an Array of Tables.

However `toml-test` seems to fail encoders if they use inline tables where appropriate instead of an Array of Tables.  This doesn't seem to be a requirement of the TOML spec itself.

An example would be an encoder providing the output

```toml
people = [{first_name = 'Bruce', last_name = 'Springsteen'}]
```

in the "valid/table/array-one" encoding test instead of

```toml
[[people]]
first_name = "Bruce"
last_name = "Springsteen"
```

Currently this fails in `toml-test` due to:

```
     Type for key 'people' differs:
       Expected:     [map[first_name:Bruce last_name:Springsteen]] ([]map[string]interface {})
       Your encoder: [map[first_name:Bruce last_name:Springsteen]] ([]interface {})
```

but aren't these simply two different ways of expressing the same thing?
