### ISSUE TITLE
long-integer test problem

### ISSUE THREAD

**Issue by ajwans** [BurntSushi/toml-test#25]
9223372036854776000 is outside the range for signed 64-bit integer.  The 0.2.0 spec requires a minimum of 64-bits for integers, the 0.3 spec clarifies this that integers should have range (−9,223,372,036,854,775,808 to 9,223,372,036,854,775,807)

**Comment by canton7** [comment]
#13 has the discussion, but agreed that breaking all languages to support javascript is a bit rubbish

**Comment by BurntSushi** [comment]
I've [reverted that change](f9ab3e2f4edfd5cb077f51ae272befe89057dcc2), sorry about that.

@redhotvengeance I think I'd be open to tweaking the range again, but only if you change the range to something within the TOML specification.

**Comment by canton7** [comment]
Thanks!

The long-float test is a bit iffy too. At that sort of precision, everything's a bit approximate. For example, C#'s "G" double format specifier (the default) outputs 3.14159265358979, while its "R" format specifier outputs 3.1415926535897931. In order to pass the test, I'd have to tailor the formatter to output exactly the number of digits you're expecting, which seems somewhat hacky.

Allowing outputs within a suitable tolerance would make the most sense, methinks.

**Comment by redhotvengeance** [comment]
@BurntSushi The issue is that JS was rounding up, pushing the expected number out of the actual range defined by the spec. How about we just round it down so it falls within the spec and is reachable by JS? I propose: `−9,223,372,036,854,775,000` to `9,223,372,036,854,775,000`

**Comment by arp242** [comment]
Current 1.0 spec reads:

> Arbitrary 64-bit signed integers (from −2^63 to 2^63−1) should be accepted and handled losslessly. If an integer cannot be represented losslessly, an error must be thrown.

Right now it checks exactly those boundary conditions in `valid/integer-long.toml`:

    answer = 9223372036854775807
    neganswer = -9223372036854775808

So all seems good? If JS can't handle that then you can use `-skip` to skip that test, and we can possible add a new test for the JS boundary condition.
