### ISSUE TITLE
Should capital base prefixes (0B, 0O, 0X) really be disallowed?

### ISSUE THREAD

**Issue by dmbaturin** [BurntSushi/toml-test#78]
Right now the tests consider capital base prefixes invalid.

```
$ grep -r 0B tests/invalid
tests/invalid/integer.multi:capital-bin = 0B0
tests/invalid/integer-capital-bin.toml:capital-bin = 0B0
```

However, the spec doesn't say they are invalid. What it says is:

>Non-negative integer values may also be expressed in hexadecimal, octal, or binary.
>In these formats, leading + is not allowed and leading zeros are allowed (after the prefix).
>Hex values are case-insensitive.

All programming languages I can remember support upper case prefixes, so it's also against the common practice.

```
$ python3
Python 3.9.5 (default, May 14 2021, 00:00:00) 
>>> 0XFF
255

 perl -e '$x = 0XFF; print "$x\n"'
255

$ node
Welcome to Node.js v14.17.0.
> 0XFF
255

$ ocaml
        OCaml version 4.12.0

# 0XFF ;;
- : int = 255

```

**Comment by arp242** [comment]
The TOML ABNF only lists the lower-case: https://github.com/toml-lang/toml/blob/1.0.0/toml.abnf#L127-L129, so according to that an upper-case isn't valid.

I don't know if there's a specific reason for that. I'll leave this open and I'll make a proposal to add upper-case too in the next version.

**Comment by dmbaturin** [comment]
Note that the ABNF file also [allows only uppercase hex digits](https://github.com/toml-lang/toml/blob/1.0.0/toml.abnf#L243), which is contrary to what the spec text says.

**Comment by arp242** [comment]
It's confusing: text in ABNF is case-insensitive, so `"A"` can also mean `"a"`. In practice though, sometimes (perhaps even often?) it is interpreted as case-sensitive, so it can be a bit murky in practice. In this case, the accompanying TOML specification text explicitly mentions hex can be lower or upper case so that removes any doubt.

For the integer prefixes it uses codepoints instead of just `"b"`, so that is case sensitive: this only applies to strings not codepoints.

**Comment by dmbaturin** [comment]
Yeah, it _may_ be one of the (IMHO, completely obnoxious) matter of taste decisions encoded in the standard. There's likewise no technical reason to disallow newlines inside inline tables, or allow trailing commas in arrays but disallows them in inline tables.

**Comment by arp242** [comment]
https://github.com/toml-lang/toml/pull/833
