### ISSUE TITLE
Multiline quoted keys

### ISSUE THREAD

**Issue by pmderodat** [BurntSushi/toml-test#87]
Hello,

`tests/invalid/key/multiline.toml` seems to imply that newline characters in quoted keys are invalid, but I can’t find such a restriction in the spec. In [1.0.0’s Keys section](https://toml.io/en/v1.0.0#keys) we can even find:
> Quoted keys follow the exact same rules as either basic strings or literal strings and allow you to use a much broader set of key names.

Shouldn’t this testcase be converted into a valid one?
Thanks!

**Comment by arp242** [comment]
With "basic strings" and "literal strings" it means only strings in the form of `"str"` and `'str'`, multiline strings are something different. You can verify this in the TOML ABNF:

    quoted-key = basic-string / literal-string
    basic-string = quotation-mark *basic-char quotation-mark
    literal-string = apostrophe *literal-char apostrophe

The multiline strings are different items.

This could probably be clarified in the specification, since someone else had a similar confusion some time ago IIRC. I'll keep this open for now so I don't forget later.

**Comment by pmderodat** [comment]
Oh I see: I was confused because I thought that it was the newline character that was forbidden in keys, whereas it’s instead the format of the key itself (regular multiline or literal multiline) that is restricted. The ABNF is indeed a good place to check, I didn’t even think about using it. Thanks a lot for the clarification, and the very fast answer! :-)

**Comment by arp242** [comment]
https://github.com/toml-lang/toml/pull/849
