### ISSUE TITLE
valid/datetime/milliseconds nanosecond precision

### ISSUE THREAD

**Issue by moorereason** [BurntSushi/toml-test#91]
The [current test](https://github.com/BurntSushi/toml-test/blob/a331ef6ee40f0c1d9d7f37581aacb58c396a7383/tests/valid/datetime/milliseconds.toml#L2) gives:
```
1987-07-05T17:45:56.6Z
```
and expects:
```
1987-07-05T17:45:56.600000Z
```

I expected nanosecond precision to be preserved and survive a round time without the value changing.

Should this behavior be enforced by toml-test or left as a implementation detail for the user to decide?

**Comment by arp242** [comment]
> I expected nanosecond precision to be preserved and survive a round time without the value changing.

`.6Z` and `.600000Z` are equivalent, right? Although the trailing zeros are a bit funky and probably shouldn't be there. Or am I not understanding how this works?

**Comment by jidicula** [comment]
> > I expected nanosecond precision to be preserved and survive a round time without the value changing.
> 
> `.6Z` and `.600000Z` are equivalent, right? Although the trailing zeros are a bit funky and probably shouldn't be there. Or am I not understanding how this works?

Not necessarily, it's a fine distinction that concerns the precision of the timekeeping device. If `.6Z` is treated as equivalent to `.600000Z`, this implies that the timekeeping device used for the timestamp is limited only to precision up to tenths of a second when in fact it measures to 10^-6 s.

**Comment by moorereason** [comment]
Thanks @jidicula for reminding me of what the spec says.

@arp242,
I agree...this feels like a trick question.  :wink:  Why am I hesitant to agree that `.6` and `.600000` are equivalent??  It's a fraction of a second, so 6 tenths of a second.  They're equal.  _I think my brain is working properly._

My question is whether the toml-test suite should fail on something the spec says is implementation dependent.  How can we avoid false negatives?

**Comment by arp242** [comment]
> Why am I hesitant to agree that .6 and .600000 are equivalent?? It's a fraction of a second, so 6 tenths of a second. They're equal. I think my brain is working properly.

I was confused about this as well. It's because "6" and "60" aren't the same when talking about seconds, minutes, or hours, so you're using two different notations. Also it's mixing base-60, base-10, and base-24 for double the fun. Stupid Babylonians and their base-60 counting system!

> My question is whether the toml-test suite should fail on something the spec says is implementation dependent. How can we avoid false negatives?

Yes, I thought about this yesterday too; but couldn't really come up with a good answer. My best is a `tests/valid/optional` directory (or something to that effect) and put all the implementation-defined and/or optional stuff in there, and possibly skip it by default too (but how do you enable it then?) Not entirely sure yet.

At the very least this test should be split in to two tests, so it's testing one thing per test.

**Comment by arp242** [comment]
I ended up just truncating these tests to millisecond precision; there's no telling what an implementation supports, and mucking about with an "optional" test directory gets pretty complicated when you consider all the different permutations.

Instead, I documented it in the README as "implementation-defined behaviour". There could perhaps be some other things in that section as well.
